services:
  iris:
    container_name: iris
    build:
      context: ./iris
      dockerfile: Dockerfile
     # target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972:1972
      - 52773:52773
      - 53773
    volumes:
      - ./iris:/home/irisowner/dev
  python:
    container_name: python
    build:
      context: ./python
      dockerfile: Dockerfile
    tty: true
    depends_on: ["iris"]
    restart: always
   # command: [ "python", "/home/python/work/connect.py", "tail", "-f", "/dev/null"]
    # ports:
    #   - 8889:8888
    volumes:
      - ./python/work:/home/python/work
  

